name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install MediaInfo (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y mediainfo

      - name: Setup MacPorts
        if: matrix.os == 'macos-latest'
        uses: melusina-org/setup-macports@v1.1.4

      - name: Install MediaInfo (macOS)
        if: matrix.os == 'macos-latest'
        run: sudo port install mediainfo

      - name: Install MediaInfoLib (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -o mediainfo.zip https://mediaarea.net/download/binary/libmediainfo0/25.04/MediaInfo_DLL_25.04_Windows_i386_WithoutInstaller.zip
          tar -xf mediainfo.zip
          echo "$PWD" >> $GITHUB_PATH

      - name: Install MediaInfo (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install mediainfo

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test