name: Publish to Maven Central
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'main' # Use your default branch (e.g., 'main' or 'master')

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install GPG and start gpg-agent
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          gpg-agent --daemon || true
          echo "GPG agent started"

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import --no-tty
          gpg --list-keys
        continue-on-error: false

      - name: Build and publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          ./gradlew publish -Pversion=${{ github.event.inputs.version }} -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_TOKEN -Psigning.keyId=$GPG_KEY_ID -Psigning.password=$GPG_PASSPHRASE

      - name: Close and release repository
        if: "!endsWith(github.event.inputs.version, '-SNAPSHOT')"
        run: ./gradlew closeAndReleaseRepository -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_TOKEN
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}